name: draggable_bottom_sheet
description: This is a bottom sheet that is partially visible onto the screen and can be dragged from there into the screen to occupy the fullscreen.
version: 0.1.2
homepage: https://github.com/Hitesh822/draggable_bottom_sheet_package.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

